// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDutQupBXg2BGnBzdfeVcF9uCvirQFB9aE',
    appId: '1:375926798538:web:7195f6bca98c2eecd39c33',
    messagingSenderId: '375926798538',
    projectId: 'e-commerce-agent-86a0e',
    authDomain: 'e-commerce-agent-86a0e.firebaseapp.com',
    storageBucket: 'e-commerce-agent-86a0e.appspot.com',
    measurementId: 'G-64KX1B9B8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpglZNy3YqhIafTOfKJQEIaJ40KvUetK4',
    appId: '1:375926798538:android:a57803d56e78ec5cd39c33',
    messagingSenderId: '375926798538',
    projectId: 'e-commerce-agent-86a0e',
    storageBucket: 'e-commerce-agent-86a0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC79WgBZWRvyp4Iy-JsDCQE_y4CyYcHAcU',
    appId: '1:375926798538:ios:0ee0bfe6f2bcd02ad39c33',
    messagingSenderId: '375926798538',
    projectId: 'e-commerce-agent-86a0e',
    storageBucket: 'e-commerce-agent-86a0e.appspot.com',
    iosClientId:
        '375926798538-kjpdl4p7bfram0uhh25853ld9bmhu8cm.apps.googleusercontent.com',
    iosBundleId: 'com.example.petsEcomPlatform',
  );
}
